name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: firefly-cpp
          template: classic
          base: header, activity, community, repositories
          config_animations: yes
          config_timezone: Europe/Ljubljana
          optimize: no
          use_prebuilt_image: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_ignored: explorer, infographile, member, worker, verified
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_skipped: GOD-GOG
          plugin_lines: yes
          plugin_repositories: yes
          plugin_repositories_featured: firefly-cpp/NiaARM firefly-cpp/cover-letter-latex
          plugin_traffic: yes
